def one():
    print("_____________")
def two():
    print("      |    ")
    print("      |    ")
    print("_____________")
def three():
    print("      |  ")
    print("      |    ")
    print("      |    ")
    print("_____________")
def four():
    print("      |      ")
    print("      |      ")
    print("      |  ")
    print("      |    ")
    print("      |    ")
    print("_____________")
def five():
    print("      _____")
    print("      |      ")
    print("      |      ")
    print("      |  ")
    print("      |    ")
    print("      |    ")
    print("_____________")
def six():
    print("      _____")
    print("      |    |  ")
    print("      |      ")
    print("      |  ")
    print("      |    ")
    print("      |    ")
    print("_____________")
def seven():
    print("      _____")
    print("      |    |  ")
    print("      |    0  ")
    print("      |  ")
    print("      |    ")
    print("      |    ")
    print("_____________")
def eight():
    print("      _____")
    print("      |    |  ")
    print("      |    0  ")
    print("      |  --|-- ")
    print("      |    ")
    print("      |    ")
    print("_____________")
def nine():
    print("      _____")
    print("      |    |  ")
    print("      |    0  ")
    print("      |  --|-- ")
    print("      |    | ")
    print("      |    ")
    print("_____________")
def ten():
    print("      _____")
    print("      |    |  ")
    print("      |    0  ")
    print("      |  --|-- ")
    print("      |    | ")
    print("      |   / [ ")
    print("_____________")
